### ISSUE TITLE
The term 'Out-PieChart' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by francescovista** [Graham-Beer/PSCharts#1]
when I run: 

`Get-Process | select -First 5 name, pm | Out-PieChart -PieChartTitle "Top 5 Windows processes running" -DisplayToScreen`

it  gives me:
 
```
Out-PieChart : The term 'Out-PieChart' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:52
+ ... t-Process |      select -First 5 name, pm |      Out-PieChart -PieCha ...
+                                                      ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Out-PieChart:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
Could you just mention in the README file how to install it? 
Thank you

**Comment by Graham-Beer** [comment]
Hi, you need to dot source the function before piping code to it. Save the function then type . ./out-piechart.ps1

**Comment by francescovista** [comment]
In case anyone else incurs in the same issue the options are 3: 
- `import-module functions.psm1` 
- drop the function under `C:\Users\<your user>\Documents\WindowsPowerShell`
-  . .\functions.ps1

**Comment by Graham-Beer** [comment]
This is a function and not a module. The way to put a function into memory is the last option,                                                                   
                       . .\functions.ps1.
